Groupdupes
jamesmontalvo3/zendir pull request #9
Opened 2017-12-20 05:55 UTC by krisfield

Deletes duplicate files but leaves most recently accessed. Builds database of deleted files. Leaves "breadcrumb" csv files in folders where files were deleted to point users to remaining file.

2018-01-10 13:34 UTC, jamesmontalvo3 commented
Why'd you delete the Vagrantfile?

2018-01-10 18:28 UTC, jamesmontalvo3 requested changes
Can you explain the difference between simDelete.py and deleteduplicates.py? Also, what is the workflow? The current README says "run scan.py" but this seems like now you do scan.py, then findDuplicates.py, then a delete script.

Also, please un-delete Vagrantfile.

2018-01-10 18:28 UTC, jamesmontalvo3 commented on scan.py
> +			stats = os.stat( filepath )
Did `os.stat( filepath )` give you an exception? Is that why you put it into this `try...except` block?

2018-01-10 18:28 UTC, jamesmontalvo3 commented on scan.py
> +		field_inserts = (filepath,rootpath,relativepath,filename,extension,bytes,created,modified,accessed, owner)
`filepath` here, `fullpath` a few lines above.

2018-01-10 18:28 UTC, jamesmontalvo3 commented on scan.py
> +		field_inserts = (filepath,rootpath,relativepath,filename,extension,bytes,created,modified,accessed, owner)
Also, `owner` has a space before it, but nothing else does. #nitpick

2018-01-10 18:28 UTC, jamesmontalvo3 commented on Vagrantfile
> -# -*- mode: ruby -*-
Don't delete this file.

2018-01-10 18:28 UTC, jamesmontalvo3 commented on scan.py
> -print "File quantities per directory are populated"
Above dupe-checking is removed (since sha1 isn't calculated on the first pass) and calculating directory totals is removed. It'd be easier to review this code if the body of the PR told me where these things moved to, or comments were left behind in the code.

2018-01-10 18:28 UTC, jamesmontalvo3 commented on findDuplicates.py
> +    except:
I believe you want `except OSError, e:` here.

2018-01-10 18:28 UTC, jamesmontalvo3 commented on findDuplicates.py
> +    except:
Maybe being more general is fine here, though. https://wiki.python.org/moin/HandlingExceptions

2018-01-10 18:28 UTC, jamesmontalvo3 commented on findDuplicates.py
> +import os, time, MySQLdb, hashlib
It looks like this file is basically a cut-paste from `scan.py`, but with sha1 being calculated separately. Correct?

2018-01-10 18:28 UTC, jamesmontalvo3 commented on update-db.py
> +#If file is does not exist in database then add it as normal
Can you elaborate on what the point of this file is?

2018-01-11 03:42 UTC, krisfield commented
- simDelete is removed now, it create a database of what would be deleted if you ran 
- deleteDuplicates but didn't actually delete anything. 
- vagrant file added back
- scan.py now allows for scan and findduplicates to be run from the same file
- scan.py now checks for any outdated files and deletes them from database before 
- scan.py has two functions now "scan_directory" and "find_duplicates". scan_directory just scans for files in the given directory. "find_duplicates" builds hashes for any file that doesn't have them
- scan.py now has a menu to allow a user to select whether they want to "scan" or "hash" their directory
- scan_directory updates an existing zendir "files" table by first finding and deleting outdated files (ones that exist in the database but not in the directory) and then scanning the drive for new files.

2018-01-12 00:09 UTC, krisfield commented
commit now adds deleting all duplicates as an option. Before deleting it checks to make sure the sha1 was created successfully. Also added a displaypath which uses the mountname instead of "/mnt/" in the file path.

2018-01-12 00:11 UTC, jamesmontalvo3 commented
More is being added to this pull request. Not sure how to proceed with reviewing.

2018-01-12 00:17 UTC, krisfield commented
No more additions expected. I'll save any other changes for a future pull request

2026-06-08 06:00 UTC, closed without merging